spring:
  datasource:
    #  rm-uf6vr2e018e95e4hz6o.mysql.rds.aliyuncs.com 外网 rm-uf6vr2e018e95e4hz.mysql.rds.aliyuncs.com
    url: jdbc:mysql://rm-uf6vr2e018e95e4hz6o.mysql.rds.aliyuncs.com:3306/dcp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Sy122812

  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2497822530@qq.com
    password: YOUR_QQ_EMAIL_AUTH_CODE  # 请替换为QQ邮箱授权码（不是QQ密码）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

logging:
  level:
    root: INFO
    com.dcp: DEBUG
    com.dcp.mapper: DEBUG
